### ISSUE TITLE
SimpleFunctionRegistry tries to convert my message again that has already been converted and fails. MessageConversionException : Could Not Convert Input

### ISSUE THREAD

**Issue by miki1029** [spring-cloud/spring-cloud-function#602]
**Describe the bug**
I used spring-cloud-stream `3.0.3.RELEASE` and recently upgraded to spring-cloud-stream `3.0.8.RELEASE`.

I am using a custom message converter that inherits `AbstractMessageConverter` and the consumer function signature is `Consumer<List<MyClass>>`.

However, after upgrading version, the following error occurred.

```
org.springframework.messaging.converter.MessageConversionException: Could Not Convert Input
```

Looking for the cause, my message has already been converted in my custom message converter, but spring tried to convert my message again in `SimpleFunctionRegistry`, and the conversion process failed here.

I think the problem is the code below.

<https://github.com/spring-cloud/spring-cloud-function/blob/v3.0.8.RELEASE/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L832>

```java
message.getPayload().getClass().isAssignableFrom(((Class<?>) rawType))
```

I think this code should be changed as below.

```java
((Class<?>) rawType).isAssignableFrom(message.getPayload().getClass())
```

Because rawType is the type I want to finally assign.
If this isn't a problem, is there something I've misunderstood?

**Sample**
```java
public class MyClassListMessageConverter extends AbstractMessageConverter {
    public MyClassListMessageConverter() {
        super(new MimeType("application", "*+avro"));
    }

    @Override
    protected boolean canConvertFrom(Message<?> message, Class<?> targetClass) {
        boolean canConvert = Optional.ofNullable(message.getHeaders().get(KafkaHeaders.RECEIVED_MESSAGE_KEY, List.class))
                                     .orElse(Collections.emptyList())
                                     .stream()
                                     .anyMatch(key -> key instanceof Key);

        canConvert = canConvert && message.getPayload() instanceof List;

        if (canConvert) {
            List<Object> payload = (List<Object>) message.getPayload();

            canConvert = payload.stream().anyMatch(o -> o instanceof Envelope)
                         || payload.stream().allMatch(o -> o instanceof KafkaNull);
        }

        return canConvert && super.canConvertFrom(message, targetClass);
    }

    @Override
    protected boolean supports(Class<?> clazz) {
        return byte[].class.equals(clazz) || List.class.equals(clazz) || Object.class.equals(clazz);
    }

    @Override
    protected Object convertFromInternal(Message<?> message, Class<?> targetClass, Object conversionHint) {
        try {
            List<Key> keys = Objects.requireNonNull(message.getHeaders().get(KafkaHeaders.RECEIVED_MESSAGE_KEY, List.class));
            List<Object> payloads = (List<Object>) message.getPayload();

            if (keys.size() != payloads.size()) {
                throw new IllegalStateException(String.format("keys and payloads size does not equal. keys size : %d, payloads size : %d", keys.size(), payloads.size()));
            }

            List<MyClass> myClasses = new ArrayList<>();

            for (int i = 0; i < payloads.size(); i++) {
                Object payload = payloads.get(i);
                if (payload instanceof KafkaNull) {
                    myClasses.add(convertToMyClass(keys.get(i), null));
                } else if (payload instanceof Envelope) {
                    myClasses.add(convertToMyClass(keys.get(i), (Envelope) payload));
                } else {
                    throw new IllegalStateException("Unknown type of payload : " + payload);
                }
            }

            return myClasses;
        } catch (Exception e) {
            log.error("{}", message);
            throw new RuntimeException(e);
        }
    }
}
```
```yaml
spring.cloud.function.definition: myConsumer

spring.cloud.stream.bindings:
  myConsumer-in-0:
    destination: mytopic
    group: mygroup
    content-type: application/*+avro
    binder: kafka
    consumer:
      batch-mode: true

spring.cloud.stream.kafka.binder:
  brokers: ${my.brokers}
  required-acks: all
  auto-create-topics: false

spring.cloud.stream.kafka.bindings:
  myConsumer-in-0:
    consumer:
      configuration:
        auto.offset.reset: earliest
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: ${my.schema-registry-url}
        specific.avro.reader: true
        max.poll.records: 100
```

**Comment by olegz** [comment]
I just tested it out but I can not reproduce it. I believe it was already addressed albeit indirectly. Our latest version is 3.0.10.RELEASE. Can you please try that and let us know?

**Comment by olegz** [comment]
I just pushed the [test](https://github.com/spring-cloud/spring-cloud-function/commit/477b5530f7502aac5882789ee1956df124848370) to validate

**Comment by miki1029** [comment]
I tried again with 3.0.10.RELEASE but it still fails.

I saw your test code.
I think your `ProductMessageConverter` is something different from my custom message converter.
Is it correct for your ProductMessageConverter to return a `Product` type?
What I intended is to return a `List<Product>`, not a `Product`.
I had to write the converter in `List<Product>` format because I had to convert the message payload with the kafka key(message headers) in the batch-mode of spring cloud stream.

**Comment by miki1029** [comment]
AS-IS
```java
message.getPayload().getClass().isAssignableFrom(((Class<?>) rawType))
```
TO-BE
```java
((Class<?>) rawType).isAssignableFrom(message.getPayload().getClass())
```
What do you think of my suggestion for this change?

**Comment by olegz** [comment]
ProductMessageConverter returns `List<Product>`. So effectively it emulates your issue.
All I am saying is that if there are issues in your custom message converter those you'd need to fix which I am sure you understand. But I am trying to figure out of there is anything else needs to be done at the framework level and until i can reproduce the issue it is hard for me to say

**Comment by olegz** [comment]
also, can you provide a stack trace with 3.0.10 so I can see if I can figure out what is happening from that?

**Comment by miki1029** [comment]
![image](https://user-images.githubusercontent.com/4443853/98268742-3eab3b80-1fd0-11eb-80f8-839f9f02d056.png)
In this screenshot, `value` has already been converted and is of type ʻArrayList<ProductCdcDto>`.
And `type` is the **stream function signature** that I declared as `List<ProductCdcDto>`. (`Consumer<List<ProductCdcDto>>`)
I no longer want the `convertInputValueIfNecessary` method to convert my `value`.

![image](https://user-images.githubusercontent.com/4443853/98269229-d872e880-1fd0-11eb-8f9d-21b51d41e364.png)
However, my value became target to conversion because the `messageNeedsConversion` method returns `true`.
My actual data type is ʻArrayList<ProductCdcDto>` and the signature type is `List<ProductCdcDto>`.
So I thought this method should return `false`.
```
message.getPayload().getClass() : ArrayList
rawType : List
```
I think the `messageNeedsConversion` method should check whether `message.getPayload().getClass()` can be assigned as `rawType`. However, on the contrary, this method is checking if the `rawType` can be assigned to `message.getPayload().getClass()`. So it behaved differently than I expected.

So I changed the **stream function signature** to ʻArrayList<ProductCdcDto>`. Then the rawType will be ʻArrayList`, which works without errors, but I think this is a stupid solution.

The stack trace is shown below.
```
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@2df9cc3d]; nested exception is org.springframework.messaging.converter.MessageConversionException: Could Not Convert Input, failedMessage=GenericMessage [payload=[{"after": null, "patch": "{\"$v\": 1,\"$set\": {\"feedDelete\": true,\"merchantUpdateDate\": {\"$date\": 1603544280000},\"updateDate\": {\"$date\": 1603574122360},\"updateId\": \"FEEDER\"}}", "source": {"version": "1.0.0.Final", "connector": "mongodb", "name": "line-shopping-mongo", "ts_ms": 1603574122000, "snapshot": "false", "db": "lineShopping", "rs": "mongod_replset_2", "collection": "products", "ord": 42, "h": 6819506133779057223}, "op": "u", "ts_ms": 1603574122368}, {"after": null, "patch": "{\"$v\": 1,\"$set\": {\"feedDelete\": true,\"merchantUpdateDate\": {\"$date\": 1603544280000},\"updateDate\": {\"$date\": 1603574122379},\"updateId\": \"FEEDER\"}}", "source": {"version": "1.0.0.Final", "connector": "mongodb", "name": "line-shopping-mongo", "ts_ms": 1603574122000, "snapshot": "false", "db": "lineShopping", "rs": "mongod_replset_2", "collection": "products", "ord": 49, "h": -4294126608777824799}, "op": "u", "ts_ms": 1603574122384}], headers={skip-type-conversion=false, kafka_offset=[7498550, 7498551], kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@4c1ea370, kafka_timestampType=[CREATE_TIME, CREATE_TIME], kafka_receivedPartitionId=[0, 0], kafka_receivedMessageKey=[{"id": "6102727040"}, {"id": "6102727178"}], kafka_batchConvertedHeaders=[{}, {}], kafka_receivedTopic=[line-shopping-mongo.lineShopping.products, line-shopping-mongo.lineShopping.products], kafka_receivedTimestamp=[1603574122476, 1603574122476], contentType=application/*+avro, kafka_groupId=com.linecorp.lsp.processor.stream.switcher.service.local}]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1902)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchErrorHandler(KafkaMessageListenerContainer.java:1607)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:1481)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1362)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1345)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1064)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:972)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@2df9cc3d]; nested exception is org.springframework.messaging.converter.MessageConversionException: Could Not Convert Input
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:111)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:104)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:69)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:384)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:75)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationBatchMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:527)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationBatchMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:497)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchOnMessage(KafkaMessageListenerContainer.java:1584)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessageWithRecordsOrList(KafkaMessageListenerContainer.java:1575)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchOnMessage(KafkaMessageListenerContainer.java:1533)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:1468)
	... 8 common frames omitted
Caused by: org.springframework.messaging.converter.MessageConversionException: Could Not Convert Input
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputValueIfNecessary(SimpleFunctionRegistry.java:821)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:601)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:453)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:441)
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:71)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:609)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:386)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:375)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:171)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:156)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeExpression(MessagingMethodInvokerHelper.java:636)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.fallbackToInvokeExpression(MessagingMethodInvokerHelper.java:629)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInvokeExceptionAndFallbackToExpressionIfAny(MessagingMethodInvokerHelper.java:613)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:584)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:477)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:355)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:108)
	... 30 common frames omitted
```

**Comment by olegz** [comment]
cool, thank you. I see what is happening. Will fix before the next release which is tomorrow

**Comment by olegz** [comment]
So the fix is in, in [3.0.11.RELEASE](https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-function-context/3.0.11.RELEASE/) of spring-cloud-function which happened today. I also added few additional tests.
I need to do something different for the master branch so will keep the issue open for now.
