### ISSUE TITLE
Reactive Flux/Mono Functions not working on AWS Lambda

### ISSUE THREAD

**Issue by Richardmbs12** [spring-cloud/spring-cloud-function#662]
**Describe the bug**
Good day, I have been facing challenges using Spring Cloud Function with Reactor specifically on AWS Lambda.
I am not sure if I am missing something, I could not find any AWS reactive function samples on https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/

All code snippets below, and sample project referenced below, worked locally using http with spring-cloud-starter-function-webflux, thus it only gives issues on AWS Lambda.

On Lambda:

Everything works when creating non reactive functions.

`    @Bean
    public Function<String, String> uppercase() {
        return String::toUpperCase;
    }`

As soon as I try using Flux or Mono from reactor:

`
    @Bean
    public Function<Flux<String>, Flux<String>> uppercase() {
        return stringFlux -> stringFlux.map(String::toUpperCase);
    }`

I get the following error on AWS Lambda:

> mbda-java-runtime-0.2.0.jar:na]
	at lambdainternal.EventHandlerLoader.loadEventHandler(EventHandlerLoader.java:613) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:122) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:226) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.main(AWSLambda.java:187) ~[aws-lambda-java-runtime-0.2.0.jar:na]
Caused by: java.lang.ClassCastException: class reactor.core.publisher.FluxPeekFuseable cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.FluxPeekFuseable and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108) ~[task/:na]
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49) ~[task/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[task/:na]
	... 21 common frames omitted

>Failed to execute CommandLineRunner: java.lang.IllegalStateException
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
**Caused by: java.lang.ClassCastException: class reactor.core.publisher.FluxPeekFuseable cannot be cast to class org.springframework.messaging.Message** (reactor.core.publisher.FluxPeekFuseable and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
	... 10 more

>Exception in thread "main" java.lang.Error: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:194)
	at lambdainternal.AWSLambda.main(AWSLambda.java:187)
Caused by: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
	at lambdainternal.runtimeapi.LambdaRuntimeClient.post(LambdaRuntimeClient.java:83)
	at lambdainternal.runtimeapi.LambdaRuntimeClient.postInitError(LambdaRuntimeClient.java:61)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:232)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
	... 1 more
END RequestId: e41e7404-9f69-49aa-9b53-ce32f0542245
REPORT RequestId: e41e7404-9f69-49aa-9b53-ce32f0542245	Duration: 1432.71 ms	Billed Duration: 1433 ms	Memory Size: 512 MB	Max Memory Used: 162 MB	Init Duration: 4337.49 ms	
RequestId: e41e7404-9f69-49aa-9b53-ce32f0542245 Error: Runtime exited with error: exit status 1
Runtime.ExitError

I tried registering the function with FunctionalSpringApplication

`@SpringBootConfiguration
public class TestFunctionalApplication implements ApplicationContextInitializer<GenericApplicationContext> {

    public static void main(String[] args) {
        FunctionalSpringApplication.run(TestFunctionalApplication.class, args);
    }

    public Function<Mono<String>, Mono<String>> uppercase() {
        return stringFlux -> stringFlux.map(String::toUpperCase);
    }

    @Override
    public void initialize(GenericApplicationContext context) {
        context.registerBean("uppercase", FunctionRegistration.class,
            () -> {
                final ResolvableType type = ResolvableType.forClassWithGenerics(Mono.class, String.class);
                return new FunctionRegistration<>(uppercase())
                    .type(new FunctionType(ResolvableType
                        .forClassWithGenerics(Function.class, type, type).getType()));
            });
    }
}`

Then I get:

>APPLICATION FAILED TO START

>Description:

>A component required a bean of type 'org.springframework.cloud.function.context.FunctionCatalog' that could not be found.

>Action:

>Consider defining a bean of type 'org.springframework.cloud.function.context.FunctionCatalog' in your configuration.

> Failed to execute CommandLineRunner: java.lang.IllegalStateException

>java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1177)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:85)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
	... 10 more

I see someone else have the same issue: https://stackoverflow.com/questions/64512879/functional-bean-registration-returns-no-bean-of-type-functioncatalog-on-aws-lamb , I tried some mentions but were not able to fix the above issue.

I tried using all the Handlers in Lambda, all gave the same result
org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest

**Sample**
Please see a sample application reproducing the issues:
https://github.com/Richardmbs12/SpringCloudFunctionLambdaReactive

Thank you for looking at my issue.

**Comment by rospe** [comment]
I face a similar issue. My AWS Lambda is using Webclient which returns a Mono<String>. I'd be fine not using Mono, but blocking is not allowed in this Function. So I am stuck right now. Thanks for your help!

`    @Bean
    public Function<Message<?>, Mono<String>> handleEvent() {
        return message -> {
            val indusEvent = mapToIndusEvent(message);
            return sendToIndus(indusEvent);
        };
    }`

this results in the following error message:

> mbda-java-runtime-0.2.0.jar:na]
> 	at lambdainternal.EventHandlerLoader.loadEventHandler(EventHandlerLoader.java:613) ~[aws-lambda-java-runtime-0.2.0.jar:na]
> 	at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:122) ~[aws-lambda-java-runtime-0.2.0.jar:na]
> 	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:226) ~[aws-lambda-java-runtime-0.2.0.jar:na]
> 	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192) ~[aws-lambda-java-runtime-0.2.0.jar:na]
> 	at lambdainternal.AWSLambda.main(AWSLambda.java:187) ~[aws-lambda-java-runtime-0.2.0.jar:na]
> Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.MonoPeekTerminal and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
> 	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108) ~[task/:na]
> 	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49) ~[task/:na]
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[task/:na]
> 	... 21 common frames omitted
> 
> Failed to execute CommandLineRunner: java.lang.IllegalStateException
> java.lang.IllegalStateException: Failed to execute CommandLineRunner
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807)
> 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
> 	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
> 	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
> Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.MonoPeekTerminal and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
> 	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108)
> 	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49)
> 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
> 	... 10 more
> 
> Exception in thread "main" java.lang.Error: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
> 	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:194)
> 	at lambdainternal.AWSLambda.main(AWSLambda.java:187)
> Caused by: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
> 	at lambdainternal.runtimeapi.LambdaRuntimeClient.post(LambdaRuntimeClient.java:83)
> 	at lambdainternal.runtimeapi.LambdaRuntimeClient.postInitError(LambdaRuntimeClient.java:61)
> 	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:232)
> 	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
> 	... 1 more

**Comment by matesebi** [comment]
I ran into the same exception trying to deploy a reactive function to AWS Lambda
```java
@Bean
public Function<Mono<String>, Mono<String>> greet() {
    return nameMono -> nameMono.map(name -> String.format("Hello %s", name));
}
```
Stack trace:
```
Failed to execute CommandLineRunner: java.lang.IllegalStateException
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:809)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.MonoPeekTerminal and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:49)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
	... 10 more
```

I was following the guide from the [docs](https://docs.spring.io/spring-cloud-function/docs/3.1.1/reference/html/spring-cloud-function.html#_aws_lambda) and the [example project](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws)

My configuration:
```
Java: 11
Spring Boot: 2.4.4
Spring Cloud: 2020.0.2
AWS Lambda Runtime: Java 11 (Corretto)
AWS Lambda Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
```

I added the `spring-cloud-function-adapter-aws` dependency
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-function-adapter-aws</artifactId>
</dependency>
```
I used the `spring-boot-maven-plugin` plugin
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot.experimental</groupId>
            <artifactId>spring-boot-thin-layout</artifactId>
            <version>1.0.17.RELEASE</version>
        </dependency>
    </dependencies>
</plugin>
```
And the `maven-shade-plugin` plugin
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.4</version>
    <configuration>
        <createDependencyReducedPom>false</createDependencyReducedPom>
        <shadedArtifactAttached>true</shadedArtifactAttached>
        <shadedClassifierName>aws</shadedClassifierName>
    </configuration>
</plugin>
```

When I switched to imperative function
```java
@Bean
    public Function<String, String> greet() {
    return name -> String.format("Hello %s!", name);
}
```
my code worked fine.

Am I missing a dependency for reactive support, or is this a bug?

**Comment by olegz** [comment]
No, but I believe your issue has to do with the unrelated bug that was discovered with Java 11 in AWS - https://github.com/spring-cloud/spring-cloud-function/commit/cf58cdc7000b1f2ca7664076fca3e79a680c2a89
Anyway, the issue is fixed, and the build is running so the fresh snapshot of spring-cloud-function (3.1.3-SNAPSHOT) will be ready in about 15-20 min. Try it out and let is know

**Comment by Richardmbs12** [comment]
Hi olegz

Thank you for your response, highly appreciated and big fan of your work and talks.

I tried 3.1.3-SNAPSHOT but unfortunately the same issue remains? 

`mbda-java-runtime-0.2.0.jar:na]
	at lambdainternal.EventHandlerLoader.loadEventHandler(EventHandlerLoader.java:613) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:122) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:226) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192) ~[aws-lambda-java-runtime-0.2.0.jar:na]
	at lambdainternal.AWSLambda.main(AWSLambda.java:187) ~[aws-lambda-java-runtime-0.2.0.jar:na]
Caused by: java.lang.ClassCastException: class reactor.core.publisher.FluxPeekFuseable cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.FluxPeekFuseable and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108) ~[task/:na]
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:47) ~[task/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[task/:na]
	... 21 common frames omitted

Failed to execute CommandLineRunner: java.lang.IllegalStateException
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
Caused by: java.lang.ClassCastException: class reactor.core.publisher.FluxPeekFuseable cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.FluxPeekFuseable and org.springframework.messaging.Message are in unnamed module of loader lambdainternal.CustomerClassLoader @3feba861)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:108)
	at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:47)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
	... 10 more

Exception in thread "main" java.lang.Error: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:194)
	at lambdainternal.AWSLambda.main(AWSLambda.java:187)
Caused by: lambdainternal.runtimeapi.LambdaRuntimeClientException: http://127.0.0.1:9001/2018-06-01/runtime/init/errorResponse code: '403'.
	at lambdainternal.runtimeapi.LambdaRuntimeClient.post(LambdaRuntimeClient.java:83)
	at lambdainternal.runtimeapi.LambdaRuntimeClient.postInitError(LambdaRuntimeClient.java:61)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:232)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
	... 1 more`

**Comment by olegz** [comment]
Hi, I am still suspecting you have an outdated snapshot, so do you see the following DEBUG messages in the logs:
```
logger.debug("AWS Environment: " + System.getenv());
``` 
and 
```
logger.debug("Will execute Lambda in Custom Runtime");
```
If you don't, that would mean you still have the old snapshot.
I'll try your sample as well

**Comment by olegz** [comment]
Ok, i managed to reproduce it. Let me see what's going on

**Comment by olegz** [comment]
So, it's a bug. Working on resolving it now, should be available shortly

**Comment by olegz** [comment]
Ok, so the fix is in and the build is running, so the fresh snapshots should be available in the next 30 min

**Comment by olegz** [comment]
So, the snapshots are available https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-function-adapter-aws/3.1.3-SNAPSHOT/, LMK

**Comment by matesebi** [comment]
I tested my example again and it is working correctly with 3.1.3-SNAPSHOT, thank you!
