### ISSUE TITLE
Spring cloud function creates a new spring boot Instance for each endpoint in the application with JDK11

### ISSUE THREAD

**Issue by bibhuprasad-photon** [spring-cloud/spring-cloud-function#706]
**Describe the bug**

Spring Cloud Function creates a new spring boot Instance for each endpoint when accessed for the very first time when used with JDK11. However it creates a single spring boot instance for all endpoints when used with JDK 1.8.

**Sample**

Attached application contains two simple azure function handlers. On the main spring application class(SampleApplication.java) , I have created a test Bean as below.
 
@Bean
@Scope("singleton")
public void testCall(){
System.out.println("-------inside test call----------");
}
Above method is called every time an endpoint is accessed for the first time. I have attached the sample code.

[Spring-cloud-function-SampleApplication-JDK11.zip](https://github.com/spring-cloud/spring-cloud-function/files/6608757/Spring-cloud-function-SampleApplication-JDK11.zip)

**Comment by olegz** [comment]
This problem has been addressed. You have split versions of spring-cloud-function in your POM

`<version>3.1.2</version>`  - for Azure adapter and  `<version>3.1.0</version>` for the rest of the s-c-function dependencies. 

Also, the newest version with additional fixes is 3.1.3 and documentation has been updates as well on how to create an Azure function - https://docs.spring.io/spring-cloud-function/docs/3.1.3/reference/html/azure.html as well as the [examples](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-azure)

**Comment by bibhuprasad-photon** [comment]
Hi @olegz, Thanks for the reply.

I updated both the versions to match 3.1.2, but the new instance of spring boot is created while using JDK11. 

I even tried using the POM file given under (https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-azure/pom.xml) , it still does not help.

**Comment by olegz** [comment]
As I mentioned before, the  latest version is 3.1.3. That is where most of it was addressed. Please upgrade and let me know

**Comment by bibhuprasad-photon** [comment]
Upgraded to 3.1.3. Behaviour is still the same. I have attached the updated pom.xml that I used for testing. 

Could you please review and let me know if there is anything else that needs to be corrected?

[pom.xml.zip](https://github.com/spring-cloud/spring-cloud-function/files/6616306/pom.xml.zip)

**Comment by olegz** [comment]
I will look but I do not see how JDK can have any effect here since there is no code that is different depending on JDK

**Comment by olegz** [comment]
Actually I see how it could happen and unfortunately there is nothing we can do about it as it is the nature of the Azure execution environment. So here are the details. 

Yes, Azure will create a new instance of `FunctionInvoker` upon each invocation which would typically trigger creation of new Spring Application Context (and we had issues with that). However, we're caching it into a static variable during the call to [initialize()](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-azure/src/main/java/org/springframework/cloud/function/adapter/azure/FunctionInvoker.java#L254) method which is also synchronized ensuring that in the event there are multiple threads we can still preserve a single instance of underlying application context. This works fine within a single JVM.

However, based on what you are describing with JDK 11 Azure may be spanning off different instance of JVM, at which point there is nothing we can do, since it's a whole other native process to which we have absolutely no visibility.

**Comment by olegz** [comment]
I am not actually sure what you're saying when you say _multiple endpoints_ or single/multiple instance of _spring boot_, so perhaps you can provide instructions on how to reproduce it locally?

**Comment by bibhuprasad-photon** [comment]
To reproduce the issue, please follow the following steps.

Steps:
1) Install and use JDK11
2) Download the attached sample application and run it using the below command. Output of the console is redirected to the output.txt file.

mvn azure-functions:run > output.txt

3) The sample application has two endpoints, which can be accessed using:

   i) http://localhost:7071/api/v1/sample/test1
   ii) http://localhost:7071/api/v1/sample/test2

4) After accessing these endpoints, please open the output.txt file. Search for word "spring boot" or "-------inside test call----------". You will notice 2 instances of these search terms. For each endpoint access it creates a separate spring boot instance. 

I have created a testCall bean, which is singleton bean in the main spring boot application class(SampleApplication.java) as below.

 @Bean
	@Scope("singleton")
	public void testCall(){
		System.out.println("-------inside test call----------");
	}

Ideally it should have created only one "testCall" bean instance after accessing both the endpoints.  As it creates separate spring boot instance while accessing each endpoint, in the output.txt, "-------inside test call----------" is printed twice indicating 2 instances of the same bean got created.

I hope this explains the issue.     

[Spring-cloud-function-SampleApplication-JDK11_updated.zip](https://github.com/spring-cloud/spring-cloud-function/files/6617032/Spring-cloud-function-SampleApplication-JDK11_updated.zip)
[output.txt](https://github.com/spring-cloud/spring-cloud-function/files/6617034/output.txt)

**Comment by olegz** [comment]
Ok, I see the issue with JDK 11. No, there is no JDK11 specific code in s-c-function.
Let me investigate

**Comment by olegz** [comment]
So, the issue is that with JDK 11, there seem to be new class loader per each invocation. This means that `FunctionInvoker` is loaded every time and the static lock makes no difference because of it.  

So we need to synchronize on one of the system classes, which we can do on the actual class name which is of type `java.lang.String`

Will push the fix shortly

**Comment by bibhuprasad-photon** [comment]
Thanks @olegz. Looking forward to the release where the fix is available.
