### ISSUE TITLE
ClassCastException when creating a non-parameterized Kotlin class implementing a functional interface

### ISSUE THREAD

**Issue by lbilger** [spring-cloud/spring-cloud-function#940]
**Describe the bug**
Given the code in the Sample section, I get the following exception:

```
java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:157) ~[spring-cloud-function-context-3.2.7.jar:3.2.7]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP GET "/uppercase/foo" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:157) ~[spring-cloud-function-context-3.2.7.jar:3.2.7]
[...]
```

This is because `KotlinLambdaToFunctionAutoConfiguration` tries to cast the `Class` object representing the `Uppercase` class to `ParameterizedType`. Instead, it would have to walk up the inheritance chain to find the actual type parameters of the `Function1` interface.

**Sample**

```kotlin
@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
    runApplication<DemoApplication>(*args)
}

@Component
class Uppercase : (String) -> String {
    override fun invoke(p1: String): String {
        return p1.uppercase()
    }
}
```

**Comment by olegz** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-function/commit/e2d89aef62b628ac865088da6a8db374e5aa4328

**Comment by lbilger** [comment]
@olegz I'm afraid this is still broken in 4.0.0 (tried it with a minimal Spring Boot 3.0.1 project created by Spring Initializr). I see you have created a unit test and it works there. I debugged my version and the difference seems to be that in `FunctionContextUtils` line 68ff., the unit test gets `null` for `definition.getSource()` and thus reaches the final `else` clause, while my version gets a `FileSystemResource` and then lands in the `else if (source instanceof Resource) {` block, sets `param` and then returns it in the `if (param != null) {` block without calling `FunctionTypeUtils.discoverFunctionTypeFromClass`.
